In [2]:
# Ví dụ thực tế - Phân tích dữ liệu học sinh
# Bài toán: Phân tích điểm số học sinh
# Dữ liệu điểm 3 môn của 5 học sinh (Toán, Lý, Hóa)
import numpy as np

scores = np.array([
    [8.5, 7.0, 9.0],  # Học sinh 1
    [9.0, 8.5, 8.0],  # Học sinh 2
    [7.5, 6.5, 7.0],  # Học sinh 3
    [9.5, 9.0, 9.5],  # Học sinh 4
    [6.0, 5.5, 6.5]   # Học sinh 5
])

subjects = ['Toán', 'Lý', 'Hóa']
students = ['An', 'Bình', 'Chi', 'Dũng', 'Hà']

# 1. Điểm trung bình mỗi học sinh
avg_per_student = np.mean(scores, axis=1)               # axis=1: tb theo hàng, axit=0: tb theo cột
for i, student in enumerate(students):
    print(f"{student}: {avg_per_student[i]:.2f}")

print("----------------")

# 2. Điểm trung bình mỗi môn
avg_per_subject = np.mean(scores, axis=0)
for i, subject in enumerate(subjects):
    print(f"{subject}: {avg_per_subject[i]:.2f}")

print("----------------")

# 3. Học sinh có điểm cao nhất
id_student_max = np.argmax(avg_per_student)
print("Học sinh có điểm cao nhất:",students[id_student_max])

# 4. Môn có điểm trung bình cao nhất
id_subject_max = np.argmax(avg_per_subject)
print("Môn có điểm trung bình cao nhất:",subjects[id_subject_max])

# 5. Tìm học sinh điểm dưới 7.0
for i, avg in enumerate(avg_per_student):
    if avg < 7:
        print(f"{students[i]}: {avg:.2f}")

An: 8.17
Bình: 8.50
Chi: 7.00
Dũng: 9.33
Hà: 6.00
----------------
Toán: 8.10
Lý: 7.30
Hóa: 8.00
----------------
Học sinh có điểm cao nhất: Dũng
Môn có điểm trung bình cao nhất: Toán
Hà: 6.00


In [4]:
# Tạo array 2D (4x3) với các số từ 1 đến 12
arr1d = np.arange(1,13)
arr2d = arr1d.reshape(4,3)
print(arr2d)
# Tính tổng mỗi hàng và mỗi cột
tong_hang = np.sum(arr2d, axis=1)
print(tong_hang)
tong_cot = np.sum(arr2d, axis=0)
print(tong_cot)
# Tìm phần tử lớn nhất và vị trí của nó
(hang, cot) = arr2d.shape
for i in (0, hang-1):
    for j in (0, cot-1):
        if arr2d[i][j] == np.max(arr2d):
            print(f"Phần tử lớn nhất: {np.max(arr2d):.2f}, ở vị trí ({i}, {j})")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 6 15 24 33]
[22 26 30]
Phần tử lớn nhất: 12.00, ở vị trí (3, 2)


In [6]:
# Cho dữ liệu nhiệt độ 7 ngày trong tuần (độ C)
temperatures = np.array([25.5, 27.2, 23.8, 29.1, 26.7, 24.3, 28.0])

# Yêu cầu:
# 1. Tính nhiệt độ trung bình
print(f"Nhiệt độ trung bình: {np.mean(temperatures):.2f}")
# 2. Tìm ngày nóng nhất và lạnh nhất
print(f"Ngày nóng nhất: {np.max(temperatures):.2f}")
print(f"Ngày lạnh nhất: {np.min(temperatures):.2f}")
# 3. Đếm số ngày nhiệt độ > 26°C
hot_day = temperatures[temperatures > 26]
print("Số ngày nhiệt độ > 26: ", hot_day.size)
# 4. Chuyển đổi sang độ F (F = C * 9/5 + 32)
temperatures_F = temperatures * 9/5 + 32
print(temperatures_F)

Nhiệt độ trung bình: 26.37
Ngày nóng nhất: 29.10
Ngày lạnh nhất: 23.80
Số ngày nhiệt độ > 26:  4
[77.9  80.96 74.84 84.38 80.06 75.74 82.4 ]
